added

diff --git a/.github/workflows/eks_argocd_github_hosted.yml b/.github/workflows/eks_argocd_github_hosted.yml
--- a/.github/workflows/eks_argocd_github_hosted.yml
+++ b/.github/workflows/eks_argocd_github_hosted.yml
@@ -2,10 +2,20 @@ name: Enterprise GitOps DevSecOps Pipeline
 
 on:
   workflow_dispatch:
+    inputs:
+      target_env:
+        description: "Select Environment"
+        required: true
+        type: choice
+        options:
+          - dev
+          - production
 
 jobs:
   devsecops:
     runs-on: self-hosted
+
+    environment: ${{ inputs.target_env }}
 
     env:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
@@ -20,28 +30,30 @@ jobs:
 
       AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
+      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
+
       ECR_REPO: employees-app-dev
 
     steps:
 
-      #################################################
-      # CHECKOUT
-      #################################################
+      #########################################################
+      # STEP 1 - CHECKOUT SOURCE CODE
+      #########################################################
       - name: Checkout Code
         uses: actions/checkout@v4
 
-      #################################################
-      # SETUP JAVA
-      #################################################
+      #########################################################
+      # STEP 2 - SETUP JAVA
+      #########################################################
       - name: Setup Java
         uses: actions/setup-java@v4
         with:
           distribution: temurin
           java-version: 17
 
-      #################################################
-      # VERSION
-      #################################################
+      #########################################################
+      # STEP 3 - SET VERSION
+      #########################################################
       - name: Set Version
         run: |
 
@@ -49,17 +61,37 @@ jobs:
 
           echo "VERSION=$VERSION" >> $GITHUB_ENV
 
-      #################################################
-      # BUILD
-      #################################################
+      #########################################################
+      # STEP 4 - VERIFY TOOLS
+      #########################################################
+      - name: Verify Installed Tools
+        run: |
+
+          java -version
+
+          mvn -version
+
+          docker --version
+
+          docker-compose --version
+
+          kubectl version --client
+
+          git --version
+
+          aws --version
+
+      #########################################################
+      # STEP 5 - MAVEN BUILD
+      #########################################################
       - name: Maven Build
         run: |
 
           mvn clean package -DskipTests
 
-      #################################################
-      # SONARQUBE
-      #################################################
+      #########################################################
+      # STEP 6 - SONARQUBE SCAN
+      #########################################################
       - name: SonarQube Scan
         run: |
 
@@ -67,28 +99,39 @@ jobs:
             -Dsonar.projectKey=employees \
             -Dsonar.projectName=employees \
             -Dsonar.host.url=${SONAR_HOST_URL} \
-            -Dsonar.login=${SONAR_TOKEN}
+            -Dsonar.login=${SONAR_TOKEN} \
+            -Dsonar.qualitygate.wait=true
 
-      #################################################
-      # TRIVY FS
-      #################################################
+      #########################################################
+      # STEP 7 - TRIVY FILE SYSTEM SCAN
+      #########################################################
       - name: Trivy FS Scan
         run: |
 
-          trivy fs .
+          trivy fs . > trivyfs.txt
 
-      #################################################
-      # DOCKER BUILD
-      #################################################
+      #########################################################
+      # STEP 8 - BUILD DOCKER IMAGE
+      #########################################################
       - name: Build Docker Image
         run: |
 
           docker build \
           -t employees-app:${VERSION} .
 
-      #################################################
-      # AWS LOGIN
-      #################################################
+          docker tag employees-app:${VERSION} employees-app:latest
+
+      #########################################################
+      # STEP 9 - TRIVY IMAGE SCAN
+      #########################################################
+      - name: Trivy Image Scan
+        run: |
+
+          trivy image employees-app:${VERSION}
+
+      #########################################################
+      # STEP 10 - CONFIGURE AWS CREDENTIALS
+      #########################################################
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
@@ -98,9 +141,52 @@ jobs:
 
           aws-region: ${{ secrets.AWS_REGION }}
 
-      #################################################
-      # ECR LOGIN
-      #################################################
+      #########################################################
+      # STEP 11 - VERIFY AWS LOGIN
+      #########################################################
+      - name: Verify AWS Identity
+        run: |
+
+          aws sts get-caller-identity
+
+      #########################################################
+      # STEP 12 - CONFIGURE KUBECONFIG
+      #########################################################
+      - name: Configure kubeconfig
+        run: |
+
+          aws eks update-kubeconfig \
+            --region ${AWS_REGION} \
+            --name ${CLUSTER_NAME}
+
+      #########################################################
+      # STEP 13 - VERIFY EKS CLUSTER
+      #########################################################
+      - name: Verify EKS Cluster
+        run: |
+
+          kubectl get nodes
+
+      #########################################################
+      # STEP 14 - APPLY ARGOCD APPLICATION ONLY ONCE
+      #########################################################
+      - name: Apply ArgoCD Application
+        run: |
+
+          kubectl get application employee-project -n argocd \
+          || kubectl apply -f argocd/argocd-app.yml
+
+      #########################################################
+      # STEP 15 - VERIFY ARGOCD APPLICATION
+      #########################################################
+      - name: Verify ArgoCD Application
+        run: |
+
+          kubectl get applications -n argocd
+
+      #########################################################
+      # STEP 16 - LOGIN TO ECR
+      #########################################################
       - name: Login to ECR
         run: |
 
@@ -111,35 +197,67 @@ jobs:
           --password-stdin \
           $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
 
-      #################################################
-      # TAG IMAGE
-      #################################################
+      #########################################################
+      # STEP 17 - TAG IMAGE FOR ECR
+      #########################################################
       - name: Tag Docker Image
         run: |
 
           docker tag employees-app:${VERSION} \
           $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:${VERSION}
 
-      #################################################
-      # PUSH IMAGE
-      #################################################
+          docker tag employees-app:${VERSION} \
+          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
+
+      #########################################################
+      # STEP 18 - PUSH IMAGE TO ECR
+      #########################################################
       - name: Push Docker Image
         run: |
 
           docker push \
           $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:${VERSION}
 
-      #################################################
-      # UPDATE K8S IMAGE
-      #################################################
-      - name: Update Deployment YAML
+          docker push \
+          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:latest
+
+      #########################################################
+      # STEP 19 - LOCAL DOCKER COMPOSE DEPLOY
+      #########################################################
+      - name: Deploy Containers
+        run: |
+
+          docker-compose down || true
+
+          docker-compose up -d
+
+      #########################################################
+      # STEP 20 - VERIFY LOCAL CONTAINERS
+      #########################################################
+      - name: Verify Running Containers
+        run: |
+
+          docker ps
+
+      #########################################################
+      # STEP 21 - UPDATE IMAGE TAG IN K8S YAML
+      #########################################################
+      - name: Update Kubernetes Deployment YAML
         run: |
 
           sed -i "s|image: .*|image: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO:${VERSION}|g" k8s/app-deployment.yml
 
-      #################################################
-      # GIT CONFIG
-      #################################################
+      #########################################################
+      # STEP 22 - VERIFY UPDATED IMAGE
+      #########################################################
+      - name: Verify Updated Deployment YAML
+        run: |
+
+          cat k8s/app-deployment.yml
+
+      #########################################################
+      # STEP 23 - CONFIGURE GIT
+      #########################################################
       - name: Configure Git
         run: |
 
@@ -147,21 +265,59 @@ jobs:
 
           git config --global user.email "github-actions@github.com"
 
-      #################################################
-      # COMMIT YAML
-      #################################################
-      - name: Commit Updated YAML
+      #########################################################
+      # STEP 24 - COMMIT UPDATED YAML
+      #########################################################
+      - name: Commit Updated Deployment YAML
         run: |
 
           git add k8s/app-deployment.yml
 
           git commit -m "Updated image version ${VERSION}" \
-          || echo "No changes"
+          || echo "No changes to commit"
 
-      #################################################
-      # PUSH CHANGES
-      #################################################
+      #########################################################
+      # STEP 25 - PUSH CHANGES TO GITHUB
+      #########################################################
       - name: Push Changes
         run: |
 
           git push origin HEAD:${GITHUB_REF_NAME}
+
+      #########################################################
+      # STEP 26 - VERIFY GIT STATUS
+      #########################################################
+      - name: Verify Git Status
+        run: |
+
+          git status
+
+      #########################################################
+      # STEP 27 - VERIFY ARGOCD SYNC
+      #########################################################
+      - name: Verify ArgoCD Sync
+        run: |
+
+          kubectl get applications -n argocd
+
+      #########################################################
+      # STEP 28 - VERIFY K8S RESOURCES
+      #########################################################
+      - name: Verify Kubernetes Resources
+        run: |
+
+          kubectl get pods -n vk67220-ns
+
+          kubectl get svc -n vk67220-ns
+
+          kubectl get ingress -n vk67220-ns
+
+          kubectl get hpa -n vk67220-ns
+
+      #########################################################
+      # STEP 29 - CLEANUP OLD DOCKER IMAGES
+      #########################################################
+      - name: Cleanup Docker Images
+        run: |
+
+          docker image prune -a -f
